name: 'Upload Build to Nunu.ai'
description: 'Upload build artifacts to Nunu.ai for automated testing'
author: 'Nunu.ai'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  api-token:
    description: 'Nunu.ai API token'
    required: true
  project-id:
    description: 'Nunu.ai project ID'
    required: true
  file:
    description: 'Path to build file to upload'
    required: true
  name:
    description: 'Build name (defaults to "Build {run_number}")'
    required: false
  platform:
    description: 'Target platform (windows, macos, linux, android, ios-native, ios-simulator, web). Auto-detected if not specified.'
    required: false
  description:
    description: 'Build description'
    required: false
  auto-delete:
    description: 'Automatically delete old builds when storage is full'
    required: false
    default: 'false'
  deletion-policy:
    description: 'Deletion policy when auto-delete is enabled: "least_recent" or "oldest"'
    required: false
    default: 'least_recent'
  upload-timeout:
    description: 'Upload timeout in minutes (1-1440)'
    required: false
  cli-version:
    description: 'Version of nunu-cli to use (default: latest)'
    required: false
    default: 'latest'

outputs:
  build-id:
    description: 'The ID of the uploaded build'
    value: ${{ steps.upload.outputs.build-id }}

runs:
  using: 'node20'
  main: 'dist/index.js'