name: Check Dist

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-dist:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Compare dist/
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build."
            echo "Please run 'npm run build' and commit the changes."
            git diff
            exit 1
          fi
      
      - name: Create test file
        run: echo "test content" > test.txt
      
      - name: Download and inspect CLI manually
        run: |
          echo "=== Downloading CLI ==="
          wget https://github.com/nunu-ai/nunu-cli/releases/download/v0.1.7/nunu-cli-v0.1.7-linux-x86_64 -O nunu-cli
          chmod +x nunu-cli
          
          echo "=== File info ==="
          ls -lh nunu-cli
          file nunu-cli
          
          echo "=== Checking dynamic dependencies ==="
          ldd nunu-cli || echo "Static binary or error"
          
          echo "=== Testing execution ==="
          ./nunu-cli --version || echo "FAILED TO RUN"
      
      - name: Test action
        uses: ./
        with:
          api-token: ${{ secrets.NUNU_API_TOKEN }}
          project-id: ${{ secrets.NUNU_PROJECT_ID }}
          file: test.txt
          name: 'Test Build'
          platform: 'linux'