name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify dist exists
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "❌ dist/index.js not found!"
            echo "Please run 'npm run build' and commit before tagging."
            exit 1
          fi
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
          prerelease: false